.ONESHELL:

model-creation-tests:
	pytest --virtual-env-directory=.\temp_venv --overwrite .\model_creation_tests

model-function-tests:
	.\temp_venv\.env\bin\activate.ps1
	pytest .\model_function_tests
	deactivate

run-all-tests: model-creation-tests model-function-tests